name: projetfinal
description: "flutterewan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^7.6.2
  google_maps_flutter: ^2.5.3
  carousel_slider: ^4.0.0
  shared_preferences: ^2.2.2
  google_maps: ^6.1.0
  google_directions_api: ^0.10.0
  geocoding: ^2.0.0
  flutter_polyline_points: ^2.0.0
  google_places_flutter: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
